log_file: %log_dir%/debug.log
log_level: info
log_error_file: %log_dir%/error.log

cache:
    enabled: true

SplotKnitModule:
    stores:
        default:
            class: Knit\Store\MongoDBStore
            database: databasechangeme

# explicitly do not minify css or js because gulp is taking care of that
SplotAssetsModule:
    minifier:
        css_enable: false
        js_enable: false
