log_file: %root_dir%/logs/%env%.log
log_level: info

cache:
    enabled: true

SplotKnitModule:
    stores:
        default:
            class: Knit\Store\MongoDBStore
            database: databasechangeme
