log_file: %log_dir%/debug.log
log_level: info
log_error_file: %log_dir%/error.log

cache:
    enabled: true

SplotKnitModule:
    stores:
        default:
            class: Knit\Store\MongoDBStore
            database: databasechangeme
